# Generated by Django 3.0 on 2022-07-20 23:30

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220720_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Email you entered is not unique!'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Username you entered is not unique!'}, max_length=150, unique=True, validators=[users.validators.UsernameValidator]),
        ),
    ]
