# Generated by Django 3.0 on 2022-07-23 23:17

import django.contrib.auth.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220721_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validators.UsernameValidator, django.contrib.auth.validators.UnicodeUsernameValidator]),
        ),
    ]
